---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```


# Overview

Contains code, data, and visualizations that allow for reproduction of "The effect of sex and endurance exercise training on the incretin signaling pathway in 17 rat tissues".

The code to generate all figures, except Fig2E, are found in `glp1a_exploration.Rmd`. Figure 2E, and other epigenetic exploration, is found in `glp1a_epi.Rmd`. The html knitouts for these notebooks can be found in the notebook folder.


## Disclaimers, Data, Questions

For questions, bug reporting, and data requests for this package, please 
[submit a new issue](https://github.com/christopherjin/exercise_glp1/issues){target="_blank"} 
and include as many details as possible. 

## Acknowledgements 

MoTrPAC is supported by the National Institutes of Health (NIH) Common
Fund through cooperative agreements managed by the National Institute of Diabetes and Digestive and Kidney Diseases (NIDDK), National Institute of Arthritis and Musculoskeletal Diseases (NIAMS), and National Institute on Aging (NIA). 

Specifically, the MoTrPAC Study is supported by NIH grants U24OD026629 (Bioinformatics Center), U24DK112349, U24DK112342, U24DK112340, U24DK112341, U24DK112326, U24DK112331, U24DK112348 (Chemical Analysis Sites), U01AR071133, U01AR071130, U01AR071124, U01AR071128, U01AR071150, U01AR071160, U01AR071158 (Clinical Centers), U24AR071113 (Consortium Coordinating Center), U01AG055133, U01AG055137 and U01AG055135 (PASS/Animal Sites).

## Data Use Agreement 

Recipients and their Agents agree that in publications using **any** data from MoTrPAC public-use data sets they will acknowledge MoTrPAC as the source of data, including the version number of the data sets used, e.g.:

* Data used in the preparation of this article were obtained from the Molecular Transducers of Physical Activity Consortium (MoTrPAC) database, which is available for public access at [motrpac-data.org](motrpac-data.org). 
* Data used in the preparation of this article were obtained from the Molecular Transducers of Physical Activity Consortium (MoTrPAC) MotrpacRatTraining6moData R package [2.0.0]. 

